oauth:
  kakao:
    client_id: 20903cb14efdb6c5b14e65c716f045ef
    redirect_uri: http://15.164.99.22/oauth/redirected/kakao
    client_secret: pv9ZImkWMTwYFR8cAsd27ifA9M7V2skY
    scope: profile_nickname
    
  naver:
    client_id: ROH3jPqXInSqBgf5XRUb
    redirect_uri: http://15.164.99.22/oauth/redirected/naver
    client_secret: SzTftZsRU8
    scope: email, nickname, name, mobile
